services:
     api-logic-server:
        image: tylerm007/dashboard-server:latest
        container_name: genai-server
        environment:
          - APILOGICPROJECT_VERBOSE=true
          - SECURITY_ENABLED=true
          - APILOGICPROJECT_VERBOSE=true
          - APILOGICPROJECT_IS_DOCKER=true
          - APILOGICPROJECT_SECURITY_ENABLED=true
          - APILOGICPROJECT_SWAGGER_HOST=172.30.3.133
          - OKTA_DOMAIN=https://ou.okta.com
          - OKTA_CLIENT_ID=0oa1crjfiwoxRYadi0x8
          - OKTA_CLIENT_SECRET=eVdobSwZgx8ANVRwPTxX6lce24t4e5ZBuAQSn_QPopvi69Xa36SWoyPjH4WcjAI7
          - OKTA_REDIRECT_URI=http://172.30.3.133:5656/auth/callback
          #- SECURITY_PROVIDER=sql
          #- APILOGICPROJECT_SECURITY_PROVIDERsql
          ## TODO: verify Database uri's here,
          - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI=mssql+pyodbc://apilogic:2Rtrzc8iLovpU!Hv8gG*@172.30.2.246:1433/dashboard?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=no&Encrypt=no
          - APILOGICPROJECT_SQLALCHEMY_DATABASE_OU_URI=mssql+pyodbc://apilogic:2Rtrzc8iLovpU!Hv8gG*@172.30.2.246:1433/ou_kash?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=no&Encrypt=no
          # postgresql://postgres:p@postgresql-service/ou_kash?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=no&Encrypt=no
          #- APILOGICPROJECT_SQLALCHEMY_DATABASE_URI_AUTHENTICATION=postgresql://postgres:p@postgresql-service/authdb
          # - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:p@mysql-service:3306/ou_kash?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=no&Encrypt=no
          # - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI_AUTHENTICATION=mysql+pymysql://root:p@mysql-service:3306/authdb
        #volumes:
           #- /home/tyler.band/dashboard:/home/api_logic_project
        expose:
          - 5656
        ports:
          - 5656:5656