export const SERVICE_CONFIG ={ 'LaneDefinition': { 'path': '/LaneDefinition' }
,'LaneRole': { 'path': '/LaneRole' }
,'ProcessDefinition': { 'path': '/ProcessDefinition' }
,'ProcessInstance': { 'path': '/ProcessInstance' }
,'ProcessMessage': { 'path': '/ProcessMessage' }
,'ProcessMessageType': { 'path': '/ProcessMessageType' }
,'ProcessPriority': { 'path': '/ProcessPriority' }
,'ProcessStatus': { 'path': '/ProcessStatus' }
,'StageInstance': { 'path': '/StageInstance' }
,'StageStatus': { 'path': '/StageStatus' }
,'Sysdiagram': { 'path': '/Sysdiagram' }
,'COMPANYTB': { 'path': '/COMPANYTB' }
,'TaskCategory': { 'path': '/TaskCategory' }
,'TaskComment': { 'path': '/TaskComment' }
,'TaskCommentType': { 'path': '/TaskCommentType' }
,'TaskDefinition': { 'path': '/TaskDefinition' }
,'TaskFlow': { 'path': '/TaskFlow' }
,'TaskInstance': { 'path': '/TaskInstance' }
,'TaskStatus': { 'path': '/TaskStatus' }
,'TaskType': { 'path': '/TaskType' }
,'ValidationResult': { 'path': '/ValidationResult' }
,'ValidationRule': { 'path': '/ValidationRule' }
,'WFActivityLog': { 'path': '/WFActivityLog' }
,'WFActivityStatus': { 'path': '/WFActivityStatus' }
,'WFApplication': { 'path': '/WFApplication' }
,'WFApplicationComment': { 'path': '/WFApplicationComment' }
,'WFApplicationMessage': { 'path': '/WFApplicationMessage' }
,'WFApplicationStatus': { 'path': '/WFApplicationStatus' }
,'WFCompany': { 'path': '/WFCompany' }
,'WFContact': { 'path': '/WFContact' }
,'WFDashboard': { 'path': '/WFDashboard' }
,'WFFile': { 'path': '/WFFile' }
,'WFFileType': { 'path': '/WFFileType' }
,'WFIngredient': { 'path': '/WFIngredient' }
,'PLANTTB': { 'path': '/PLANTTB' }
,'WFPlant': { 'path': '/WFPlant' }
,'WFPriority': { 'path': '/WFPriority' }
,'WFProduct': { 'path': '/WFProduct' }
,'WFQuote': { 'path': '/WFQuote' }
,'WFQuoteItem': { 'path': '/WFQuoteItem' }
,'WFQuoteStatus': { 'path': '/WFQuoteStatus' }
,'WFRole': { 'path': '/WFRole' }
,'WFUser': { 'path': '/WFUser' }
,'WorkflowHistory': { 'path': '/WorkflowHistory' }
 };