export const SERVICE_CONFIG ={ 'AchAuthToken': { 'path': '/AchAuthToken' }
,'AchPlaidLambdaResponse': { 'path': '/AchPlaidLambdaResponse' }
,'AchStripePayment': { 'path': '/AchStripePayment' }
,'AchStripePaymentDetail': { 'path': '/AchStripePaymentDetail' }
,'BarCode': { 'path': '/BarCode' }
,'Billing': { 'path': '/Billing' }
,'COMPANYADDRESSTB': { 'path': '/COMPANYADDRESSTB' }
,'COMPANYCERTDETAIL': { 'path': '/COMPANYCERTDETAIL' }
,'COMPANYCOMMENT': { 'path': '/COMPANYCOMMENT' }
,'COMPANYFEECOMMENT': { 'path': '/COMPANYFEECOMMENT' }
,'COMPANYFEESTRUCTURE': { 'path': '/COMPANYFEESTRUCTURE' }
,'COMPANYHOLDTB': { 'path': '/COMPANYHOLDTB' }
,'COMPANYOTHERNAME': { 'path': '/COMPANYOTHERNAME' }
,'COMPANYSTATUSTB': { 'path': '/COMPANYSTATUSTB' }
,'COMPANYTB': { 'path': '/COMPANYTB' }
,'COPRIVATELABELFEEDETAIL': { 'path': '/COPRIVATELABELFEEDETAIL' }
,'CoPackerFacilitiesCategory': { 'path': '/CoPackerFacilitiesCategory' }
,'CoPackerFacilitiesLocation': { 'path': '/CoPackerFacilitiesLocation' }
,'CoPackerFacility': { 'path': '/CoPackerFacility' }
,'CompanyPlantOption': { 'path': '/CompanyPlantOption' }
,'CompanycontactsTb': { 'path': '/CompanycontactsTb' }
,'FormulaComponent': { 'path': '/FormulaComponent' }
,'FormulaProduct': { 'path': '/FormulaProduct' }
,'FormulaSubmissionComponent': { 'path': '/FormulaSubmissionComponent' }
,'FormulaSubmissionPlant': { 'path': '/FormulaSubmissionPlant' }
,'INVOICEFEE': { 'path': '/INVOICEFEE' }
,'INVOICEFEESDETAIL': { 'path': '/INVOICEFEESDETAIL' }
,'LabelBarcode': { 'path': '/LabelBarcode' }
,'LabelComment': { 'path': '/LabelComment' }
,'LabelOption': { 'path': '/LabelOption' }
,'LabelTb': { 'path': '/LabelTb' }
,'MERCHCOMMENT': { 'path': '/MERCHCOMMENT' }
,'MERCHOTHERNAME': { 'path': '/MERCHOTHERNAME' }
,'MERCHTB': { 'path': '/MERCHTB' }
,'MiniCRMAction': { 'path': '/MiniCRMAction' }
,'OWNSTB': { 'path': '/OWNSTB' }
,'PENDINGINFOTB': { 'path': '/PENDINGINFOTB' }
,'PERSONADDRESSTB': { 'path': '/PERSONADDRESSTB' }
,'PERSONJOBSTATUSTB': { 'path': '/PERSONJOBSTATUSTB' }
,'PERSONJOBTB': { 'path': '/PERSONJOBTB' }
,'PERSONTB': { 'path': '/PERSONTB' }
,'PLANTADDRESSTB': { 'path': '/PLANTADDRESSTB' }
,'PLANTCERTDETAIL': { 'path': '/PLANTCERTDETAIL' }
,'PLANTCOMMENT': { 'path': '/PLANTCOMMENT' }
,'PLANTFEECOMMENT': { 'path': '/PLANTFEECOMMENT' }
,'PLANTFEESTRUCTURE': { 'path': '/PLANTFEESTRUCTURE' }
,'PLANTFEESTRUCTUREOUT': { 'path': '/PLANTFEESTRUCTUREOUT' }
,'PLANTHOLDTB': { 'path': '/PLANTHOLDTB' }
,'PLANTTB': { 'path': '/PLANTTB' }
,'PRIVATELABELBILL': { 'path': '/PRIVATELABELBILL' }
,'PrivateLabelTemplate': { 'path': '/PrivateLabelTemplate' }
,'ProducedIn1Tb': { 'path': '/ProducedIn1Tb' }
,'ProductJob': { 'path': '/ProductJob' }
,'ProductJobLineItem': { 'path': '/ProductJobLineItem' }
,'PurchaseOrder': { 'path': '/PurchaseOrder' }
,'RCTB': { 'path': '/RCTB' }
,'StripeCustomer': { 'path': '/StripeCustomer' }
,'ThirdPartyBillingCompany': { 'path': '/ThirdPartyBillingCompany' }
,'USEDIN1TB': { 'path': '/USEDIN1TB' }
,'VISIT': { 'path': '/VISIT' }
,'VISITSCOMMENT': { 'path': '/VISITSCOMMENT' }
,'YoshonInfo': { 'path': '/YoshonInfo' }
 };