export const SERVICE_CONFIG ={ 'COMPANYADDRESSTB': { 'path': '/COMPANYADDRESSTB' }
,'COMPANYTB': { 'path': '/COMPANYTB' }
,'CompanyApplication': { 'path': '/CompanyApplication' }
,'FormulaProduct': { 'path': '/FormulaProduct' }
,'FormulaSubmissionComponent': { 'path': '/FormulaSubmissionComponent' }
,'FormulaSubmissionPlant': { 'path': '/FormulaSubmissionPlant' }
,'LabelTb': { 'path': '/LabelTb' }
,'LaneRole': { 'path': '/LaneRole' }
,'LaneDefinition': { 'path': '/LaneDefinition' }
,'MERCHTB': { 'path': '/MERCHTB' }
,'OWNSTB': { 'path': '/OWNSTB' }
,'PLANTADDRESSTB': { 'path': '/PLANTADDRESSTB' }
,'PLANTCERTDETAIL': { 'path': '/PLANTCERTDETAIL' }
,'PLANTCOMMENT': { 'path': '/PLANTCOMMENT' }
,'PLANTTB': { 'path': '/PLANTTB' }
,'ProcessDefinition': { 'path': '/ProcessDefinition' }
,'ProcessInstance': { 'path': '/ProcessInstance' }
,'ProcessMessage': { 'path': '/ProcessMessage' }
,'ProcessMessageType': { 'path': '/ProcessMessageType' }
,'ProcessPriority': { 'path': '/ProcessPriority' }
,'ProcessStatus': { 'path': '/ProcessStatus' }
,'ProducedIn1Tb': { 'path': '/ProducedIn1Tb' }
,'RoleAssigment': { 'path': '/RoleAssigment' }
,'StageInstance': { 'path': '/StageInstance' }
,'StageStatus': { 'path': '/StageStatus' }
,'TaskCategory': { 'path': '/TaskCategory' }
,'TaskComment': { 'path': '/TaskComment' }
,'TaskCommentType': { 'path': '/TaskCommentType' }
,'TaskDefinition': { 'path': '/TaskDefinition' }
,'TaskFlow': { 'path': '/TaskFlow' }
,'TaskInstance': { 'path': '/TaskInstance' }
,'TaskStatus': { 'path': '/TaskStatus' }
,'TaskType': { 'path': '/TaskType' }
,'USEDIN1TB': { 'path': '/USEDIN1TB' }
,'WFActivityLog': { 'path': '/WFActivityLog' }
,'WFActivityStatus': { 'path': '/WFActivityStatus' }
,'WFApplication': { 'path': '/WFApplication' }
,'WFApplicationComment': { 'path': '/WFApplicationComment' }
,'WFApplicationMessage': { 'path': '/WFApplicationMessage' }
,'WFApplicationStatus': { 'path': '/WFApplicationStatus' }
,'WFCompany': { 'path': '/WFCompany' }
,'WFContact': { 'path': '/WFContact' }
,'WFFile': { 'path': '/WFFile' }
,'WFFileType': { 'path': '/WFFileType' }
,'WFIngredient': { 'path': '/WFIngredient' }
,'WFPriority': { 'path': '/WFPriority' }
,'WFProduct': { 'path': '/WFProduct' }
,'WFQuote': { 'path': '/WFQuote' }
,'WFQuoteItem': { 'path': '/WFQuoteItem' }
,'WFQuoteStatus': { 'path': '/WFQuoteStatus' }
,'WFRole': { 'path': '/WFRole' }
,'WFUSERADMIN': { 'path': '/WFUSERADMIN' }
,'WFUSERROLE': { 'path': '/WFUSERROLE' }
,'WFUser': { 'path': '/WFUser' }
,'WorkflowHistory': { 'path': '/WorkflowHistory' }
 };