// Copy this text, paste to https://dbdiagram.io/d
// Or, https://databasediagram.com/app
// Or, view in VSCode with extension: "DBML Live Preview"

Table DeletedJotFormCompany {
    JotFormId INTEGER [primary key]
    submission_id VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    submission_date DATETIME 
    OUcertified BOOLEAN 
    everCertified BOOLEAN 
    agencyName VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyName VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyAddress VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyAddress2 VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyCity VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyCountry VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyState VARCHAR(25) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyRegion VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyProvince VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyPhone VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ZipPostalCode VARCHAR(15) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    companyWebsite VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsPrimaryContact BOOLEAN 
    contactFirst VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    contactLast VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    contactPhone VARCHAR(25) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    contactEmail VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    billingContact VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    billingContactFirst VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    billingContactLast VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    billingContactPhone VARCHAR(25) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    billingContactEmail VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    jobTitle VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    contactFirst1 VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    contactLast1 VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    contactPhone1 VARCHAR(25) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    contactEmail1 VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    jobTitle1 VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    whatWould TEXT(2147483647) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    whichCategory VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    whereDidHear VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    pleaseSpecify TEXT(2147483647) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    copack VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    listInCopack BOOLEAN 
    veganCert BOOLEAN 
    areThere BOOLEAN 
    numberOfPlants INTEGER 
    formName VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    language VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    status VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    kashrusLink VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    submissionurl VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table DeletedWFRole {
    UserRole VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    Role VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    }

Table DeletedWFUSERROLE {
    UserName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    UserRole VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    }

Table DeletedWFUser {
    Username VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    Email VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    FullName VARCHAR(200) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsActive BOOLEAN 
    CreatedDate DATETIME2 
    LastLoginDate DATETIME2 
    }

Table EventAction {
    EventId INTEGER [primary key]
    EventKey VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    TaskInstanceId INTEGER 
    EventStatus VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    EventType VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    EventMessage VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    StartDate DATETIME2 
    DueDate DATETIME2 
    IsResolved BOOLEAN 
    ResolvedDate DATETIME2 
    }

Table TaskInstance {
    TaskInstanceId INTEGER [primary key]
    TaskDefinitionId INTEGER 
    ApplicationId INTEGER 
    StageId INTEGER 
    Status VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    AssignedTo VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    StartedDate DATETIME2 
    CompletedDate DATETIME2 
    DurationMinutes INTEGER 
    Result VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ResultData VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ErrorMessage VARCHAR(1000) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    RetryCount INTEGER 
    ModifiedDate DATETIME2 
    CompletedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CompletedCapacity VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsVisible BOOLEAN 
    ActiveStartDate DATETIME2 
    }

Table ProcessDefinition {
    ProcessId INTEGER [primary key]
    ProcessName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ProcessVersion VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Description VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsActive BOOLEAN 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table RoleAssigment {
    RoleAssigmentID INTEGER [primary key]
    ApplicationId INTEGER 
    Role VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Assignee VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(32) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsPrimary BOOLEAN 
    }

Table WFApplication {
    ApplicationID INTEGER [primary key]
    ApplicationNumber INTEGER 
    CompanyID INTEGER 
    PlantID INTEGER 
    SubmissionDate DATE 
    Status VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Priority VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ApplicationType NCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ExternalAppRef INTEGER 
    WFLinkedApp INTEGER 
    }

Table StageDefinition {
    StageId INTEGER [primary key]
    StageName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    StageDescription VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    EstimatedDurationDays INTEGER 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table StageStatus {
    StatusCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    StatusDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table Sysdiagram {
    name VARCHAR(128) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    principal_id INTEGER 
    diagram_id INTEGER [primary key]
    version INTEGER 
    definition BLOB 
    }

Table TaskCategory {
    TaskCategoryCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    TaskCategoryDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskDefinition {
    TaskId INTEGER [primary key]
    ProcessDefinitionId INTEGER 
    TaskName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    TaskType VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    TaskCategory VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Sequence INTEGER 
    StageDefinitionId INTEGER 
    IsParallel BOOLEAN 
    AssigneeRole VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    EstimatedDurationMinutes INTEGER 
    IsRequired BOOLEAN 
    AutoComplete BOOLEAN 
    Description VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    PreScriptJson VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    PostScriptJson VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskType {
    TaskTypeCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    TaskTypeDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskEvent {
    TaskEventId INTEGER [primary key]
    ApplicationId INTEGER 
    TaskInstanceId INTEGER 
    Action VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    PreviousStatus VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    NewStatus VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ActionBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ActionDate DATETIME2 
    ActionReason VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Details VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskFlow {
    FlowId INTEGER [primary key]
    FromTaskId INTEGER 
    ToTaskId INTEGER 
    Condition VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsDefault BOOLEAN 
    }

Table TaskStatus {
    StatusCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    StatusDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskRole {
    RoleCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    RoleDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    groupAssignment BOOLEAN 
    }

Table WFPriority {
    PriorityCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    PriorityDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFApplicationStatus {
    StatusCode VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    StatusDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFApplicationMessage {
    MessageID INTEGER [primary key]
    ApplicationID INTEGER 
    FromUser VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ToUser VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    MessageText VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    MessageType VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Priority VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    SentDate DATETIME2 
    TaskInstanceId INTEGER 
    }

Table WFFile {
    FileID INTEGER [primary key]
    ApplicationID INTEGER 
    FileName VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    FileType VARCHAR(5) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    FileSize VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    UploadedDate DATETIME2 
    Tag VARCHAR(200) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsProcessed BOOLEAN 
    RecordCount INTEGER 
    FilePath VARCHAR(1000) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFFileType {
    FileType VARCHAR(5) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    FileTypeName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFQuote {
    QuoteID INTEGER [primary key]
    ApplicationID INTEGER 
    QuoteNumber VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    TotalAmount DECIMAL 
    ValidUntil DATE 
    Status VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    LastUpdatedDate DATE 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFQuoteStatus {
    StatusCode VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    StatusDesc VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFQuoteItem {
    QuoteItemID INTEGER [primary key]
    QuoteID INTEGER 
    Description VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Amount DECIMAL 
    SortOrder INTEGER 
    }

Table WFUserProfile {
    Username VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    Profile TEXT(2147483647) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    LastModDate DATETIME2 
    }



// Relationships
    Ref: DeletedWFUSERROLE.(UserName) > DeletedWFUser.(Username)
    Ref: DeletedWFUSERROLE.(UserRole) > DeletedWFRole.(UserRole)
    Ref: EventAction.(TaskInstanceId) > TaskInstance.(TaskInstanceId)
    Ref: TaskInstance.(ApplicationId) > WFApplication.(ApplicationID)
    Ref: TaskInstance.(StageId) > StageDefinition.(StageId)
    Ref: TaskInstance.(Status) > TaskStatus.(StatusCode)
    Ref: TaskInstance.(TaskDefinitionId) > TaskDefinition.(TaskId)
    Ref: RoleAssigment.(ApplicationId) > WFApplication.(ApplicationID)
    Ref: WFApplication.(Priority) > WFPriority.(PriorityCode)
    Ref: WFApplication.(Status) > WFApplicationStatus.(StatusCode)
    Ref: TaskDefinition.(ProcessDefinitionId) > ProcessDefinition.(ProcessId)
    Ref: TaskDefinition.(StageDefinitionId) > StageDefinition.(StageId)
    Ref: TaskDefinition.(TaskCategory) > TaskCategory.(TaskCategoryCode)
    Ref: TaskDefinition.(TaskType) > TaskType.(TaskTypeCode)
    Ref: TaskEvent.(ApplicationId) > WFApplication.(ApplicationID)
    Ref: TaskEvent.(TaskInstanceId) > TaskInstance.(TaskInstanceId)
    Ref: TaskFlow.(FromTaskId) > TaskDefinition.(TaskId)
    Ref: TaskFlow.(ToTaskId) > TaskDefinition.(TaskId)
    Ref: WFApplicationMessage.(ApplicationID) > WFApplication.(ApplicationID)
    Ref: WFApplicationMessage.(Priority) > WFPriority.(PriorityCode)
    Ref: WFFile.(ApplicationID) > WFApplication.(ApplicationID)
    Ref: WFFile.(FileType) > WFFileType.(FileType)
    Ref: WFQuote.(ApplicationID) > WFApplication.(ApplicationID)
    Ref: WFQuote.(Status) > WFQuoteStatus.(StatusCode)
    Ref: WFQuoteItem.(QuoteID) > WFQuote.(QuoteID)
