// Copy this text, paste to https://dbdiagram.io/d
// Or, https://databasediagram.com/app
// Or, view in VSCode with extension: "DBML Live Preview"

Table EventAction {
    EventId INTEGER [primary key]
    EventKey VARCHAR(250) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    TaskInstanceId INTEGER 
    EventStatus VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    EventType VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    EventMessage VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    StartDate DATETIME2 
    DueDate DATETIME2 
    IsResolved BOOLEAN 
    ResolvedDate DATETIME2 
    }

Table TaskInstance {
    TaskInstanceId INTEGER [primary key]
    TaskDefinitionId INTEGER 
    StageId INTEGER 
    Status VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    AssignedTo VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    StartedDate DATETIME2 
    CompletedDate DATETIME2 
    _DurationMinutes INTEGER 
    Result VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ResultData VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ErrorMessage VARCHAR(1000) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    RetryCount INTEGER 
    }

Table ProcessDefinition {
    ProcessId INTEGER [primary key]
    ProcessName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ProcessVersion VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Description VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsActive BOOLEAN 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table RoleAssigment {
    RoleAssigmentID INTEGER [primary key]
    ApplicationId INTEGER 
    Role VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Assignee VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(32) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFApplication {
    ApplicationID INTEGER [primary key]
    ApplicationNumber INTEGER 
    CompanyID INTEGER 
    PlantID INTEGER 
    SubmissionDate DATE 
    Status VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Priority VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table StageDefinition {
    StageId INTEGER [primary key]
    StageName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    StageDescription VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    EstimatedDurationDays INTEGER 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table StageInstance {
    StageInstanceId INTEGER [primary key]
    ApplicationId INTEGER 
    StageDefinitionId INTEGER 
    Status VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    StartedDate DATETIME2 
    CompletedDate DATETIME2 
    }

Table StageStatus {
    StatusCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    StatusDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table Sysdiagram {
    name VARCHAR(128) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    principal_id INTEGER 
    diagram_id INTEGER [primary key]
    version INTEGER 
    definition BLOB 
    }

Table TaskCategory {
    TaskCategoryCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    TaskCategoryDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskDefinition {
    TaskId INTEGER [primary key]
    ProcessDefinitionId INTEGER 
    TaskName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    TaskType VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    TaskCategory VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Sequence INTEGER 
    StageDefinitionId INTEGER 
    IsParallel BOOLEAN 
    AssigneeRole VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    EstimatedDurationMinutes INTEGER 
    IsRequired BOOLEAN 
    AutoComplete BOOLEAN 
    Description VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    PreScriptJson VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    PostScriptJson VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskType {
    TaskTypeCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    TaskTypeDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskFlow {
    FlowId INTEGER [primary key]
    FromTaskId INTEGER 
    ToTaskId INTEGER 
    Condition VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsDefault BOOLEAN 
    }

Table TaskStatus {
    StatusCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    StatusDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table TaskRole {
    RoleCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    RoleDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFPriority {
    PriorityCode VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    PriorityDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFApplicationStatus {
    StatusCode VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    StatusDescription VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFApplicationMessage {
    MessageID INTEGER [primary key]
    ApplicationID INTEGER 
    FromUser VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ToUser VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    MessageText VARCHAR COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    MessageType VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Priority VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    SentDate DATETIME2 
    TaskInstanceId INTEGER 
    }

Table WFFile {
    FileID INTEGER [primary key]
    ApplicationID INTEGER 
    FileName VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    FileType VARCHAR(5) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    FileSize VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    UploadedDate DATE 
    Tag VARCHAR(200) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsProcessed BOOLEAN 
    RecordCount INTEGER 
    FilePath VARCHAR(1000) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CCreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFFileType {
    FileType VARCHAR(5) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    FileTypeName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFQuote {
    QuoteID INTEGER [primary key]
    ApplicationID INTEGER 
    QuoteNumber VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    TotalAmount DECIMAL 
    ValidUntil DATE 
    Status VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    LastUpdatedDate DATE 
    CreatedDate DATETIME2 
    CreatedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    ModifiedDate DATETIME2 
    ModifiedBy VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFQuoteStatus {
    StatusCode VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    StatusDesc VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    }

Table WFQuoteItem {
    QuoteItemID INTEGER [primary key]
    QuoteID INTEGER 
    Description VARCHAR(500) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    Amount DECIMAL 
    SortOrder INTEGER 
    }

Table WFRole {
    UserRole VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    Role VARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    }

Table WFUSERADMIN {
    UserName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    AdminUserName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsPrimary BOOLEAN 
    CreatedDate DATETIME2 
    }

Table WFUser {
    Username VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    Email VARCHAR(255) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    FullName VARCHAR(200) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    IsActive BOOLEAN 
    CreatedDate DATETIME2 
    LastLoginDate DATETIME2 
    }

Table WFUSERROLE {
    UserName VARCHAR(100) COLLATE "SQL_Latin1_General_CP1_CI_AS" [primary key]
    UserRole VARCHAR(10) COLLATE "SQL_Latin1_General_CP1_CI_AS" 
    CreatedDate DATETIME2 
    }



// Relationships
    Ref: EventAction.(TaskInstanceId) < TaskInstance.(TaskInstanceId)
    Ref: TaskInstance.(StageId) < StageInstance.(StageInstanceId)
    Ref: TaskInstance.(Status) < TaskStatus.(StatusCode)
    Ref: TaskInstance.(TaskDefinitionId) < TaskDefinition.(TaskId)
    Ref: RoleAssigment.(ApplicationId) < WFApplication.(ApplicationID)
    Ref: WFApplication.(Priority) < WFPriority.(PriorityCode)
    Ref: WFApplication.(Status) < WFApplicationStatus.(StatusCode)
    Ref: StageInstance.(ApplicationId) < WFApplication.(ApplicationID)
    Ref: StageInstance.(StageDefinitionId) < StageDefinition.(StageId)
    Ref: StageInstance.(Status) < StageStatus.(StatusCode)
    Ref: TaskDefinition.(ProcessDefinitionId) < ProcessDefinition.(ProcessId)
    Ref: TaskDefinition.(StageDefinitionId) < StageDefinition.(StageId)
    Ref: TaskDefinition.(TaskCategory) < TaskCategory.(TaskCategoryCode)
    Ref: TaskDefinition.(TaskType) < TaskType.(TaskTypeCode)
    Ref: TaskFlow.(FromTaskId) < TaskDefinition.(TaskId)
    Ref: TaskFlow.(ToTaskId) < TaskDefinition.(TaskId)
    Ref: WFApplicationMessage.(ApplicationID) < WFApplication.(ApplicationID)
    Ref: WFApplicationMessage.(Priority) < WFPriority.(PriorityCode)
    Ref: WFFile.(ApplicationID) < WFApplication.(ApplicationID)
    Ref: WFFile.(FileType) < WFFileType.(FileType)
    Ref: WFQuote.(ApplicationID) < WFApplication.(ApplicationID)
    Ref: WFQuote.(Status) < WFQuoteStatus.(StatusCode)
    Ref: WFQuoteItem.(QuoteID) < WFQuote.(QuoteID)
    Ref: WFUSERADMIN.(AdminUserName) < WFUser.(Username)
    Ref: WFUSERADMIN.(UserName) < WFUser.(Username)
    Ref: WFUSERROLE.(UserName) < WFUser.(Username)
    Ref: WFUSERROLE.(UserRole) < WFRole.(UserRole)
